(() => {
  'use strict';
  const CUSTOM='qol_roadmap_profiles_v1', SELECTED='qol_roadmap_selected_v1', PANEL='qol-roadmaps-container', DIALOG='qol-roadmaps-dialog-layer';
  const BUILDINGS=[
    ['Warehouse',10,20],['Granary',11,20],['Main Building',15,20],['Rally Point',16,20],['Marketplace',17,20],['Embassy',18,20],['Barracks',19,20],['Stable',20,20],['Workshop',21,20],['Academy',22,20],['Cranny',23,10,true],['Town Hall',24,20],['Residence',25,20],['Palace',26,20],['Treasury',27,20],['Trade Office',28,20],['Sawmill',5,5],['Brickyard',6,5],['Iron Foundry',7,5],['Grain Mill',8,5],['Bakery',9,5],['Smithy',12,20],['Tribe Wall',null,20,false,true],['Tournament Square',null,20],['Stonemason',null,20],['Trapper',null,20],['Brewery',null,20],['Horse Drinking Trough',null,20],['Great Barracks',null,20],['Great Stable',null,20],['Great Warehouse',null,20],['Great Granary',null,20],['Wonder of the World',null,100]
  ].map(([name,id,max,repeatable=false,tribeWall=false])=>({name,id,max,repeatable,tribeWall}));
  const clean=v=>String(v??'').replace(/\s+/g,' ').trim(), norm=v=>clean(v).toLowerCase();
  const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');
  const read=()=>{try{const v=JSON.parse(localStorage.getItem(CUSTOM)||'{}');return v&&typeof v==='object'&&!Array.isArray(v)?v:{}}catch(_){return{}}};
  const write=v=>{try{localStorage.setItem(CUSTOM,JSON.stringify(v));return true}catch(e){console.warn('[APES Roadmaps Editor] Save failed',e);return false}};
  const selected=()=>{try{return clean(localStorage.getItem(SELECTED))}catch(_){return''}};
  const setSelected=id=>{try{localStorage.setItem(SELECTED,id)}catch(_){}};
  const state=()=>{const id=selected(),custom=read();return{id,custom,roadmap:custom[id]||null}};
  const entry=name=>BUILDINGS.find(x=>norm(x.name)===norm(name))||BUILDINGS[0];
  const refresh=()=>window.APES?.roadmaps?.open?.();
  function toast(text,type='success'){document.querySelector('.qol-rme-toast')?.remove();const n=document.createElement('div');n.className=`qol-rme-toast ${type}`;n.textContent=text;document.body.appendChild(n);setTimeout(()=>n.remove(),2300)}
  function closeDialog(){document.getElementById(DIALOG)?.remove()}
  function dialog(title,body,confirm='Save'){
    closeDialog();const l=document.createElement('div');l.id=DIALOG;l.innerHTML=`<div class="qol-rm-dialog qol-rme-dialog" role="dialog" aria-modal="true"><div class="qol-rm-dialog-head">${esc(title)}</div><div class="qol-rm-dialog-body">${body}<div class="qol-rm-dialog-status"></div></div><div class="qol-rm-dialog-actions"><div class="qol-rm-action qol-secondary" data-rme-cancel role="button" tabindex="0">Cancel</div><div class="qol-rm-action" data-rme-confirm role="button" tabindex="0">${esc(confirm)}</div></div></div>`;
    l.querySelector('[data-rme-cancel]').onclick=closeDialog;l.onclick=e=>{if(e.target===l)closeDialog()};l.onkeydown=e=>{if(e.key==='Escape')closeDialog();if((e.key==='Enter'||e.key===' ')&&e.target.matches('[role="button"],[role="checkbox"]')){e.preventDefault();e.target.click()}};document.body.appendChild(l);return l;
  }
  function details(create=false){
    const s=state(),src=create?{name:'',description:''}:s.roadmap;if(!src)return;
    const l=dialog(create?'Create Roadmap':'Edit Roadmap Details',`<label>Name</label><input data-name maxlength="90"><label>Description</label><textarea data-desc rows="4" maxlength="500"></textarea>`,create?'Create Roadmap':'Save Changes');
    const name=l.querySelector('[data-name]'),desc=l.querySelector('[data-desc]'),status=l.querySelector('.qol-rm-dialog-status');name.value=src.name||'';desc.value=src.description||'';
    const save=()=>{const n=clean(name.value);if(!n){status.textContent='Enter a roadmap name.';name.focus();return}const c=read();if(create){const id=`custom_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,7)}`;c[id]={name:n,description:clean(desc.value),steps:[]};write(c);setSelected(id)}else{if(!c[s.id])return;c[s.id].name=n;c[s.id].description=clean(desc.value);write(c)}closeDialog();refresh();toast(create?'Roadmap created.':'Roadmap updated.')};
    l.querySelector('[data-rme-confirm]').onclick=save;name.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();save()}};name.focus();if(!create)name.select();
  }
  const options=sel=>BUILDINGS.map(x=>`<option${norm(x.name)===norm(sel)?' selected':''}>${esc(x.name)}</option>`).join('');
  function highest(steps,name,instance,before=steps.length){let h=0;for(let i=0;i<Math.min(before,steps.length);i++){const x=steps[i];if(x?.type==='building'&&norm(x.building)===norm(name)&&(Number(x.instance)||0)===(Number(instance)||0))h=Math.max(h,Number(x.level)||0)}return h}
  const makeStep=(b,l,i)=>({type:'building',building:b.name,buildingId:b.id,level:l,...(b.repeatable?{instance:i}:{}),...(b.tribeWall?{tribeWall:true}:{})});
  function building(index=null){
    const s=state();if(!s.roadmap)return;const editing=Number.isInteger(index),old=editing?s.roadmap.steps[index]:null,initial=old?.type==='building'?old:{building:'Warehouse',level:1,instance:1},b0=entry(initial.building);
    const l=dialog(editing?'Edit Building Step':'Add Building Step',`<div class="qol-rme-grid"><div><label>Building</label><select data-building>${options(initial.building)}</select></div><div><label>Level</label><input data-level type="number" min="1" max="${b0.max}" value="${Number(initial.level)||1}"></div><div data-instance-wrap><label>Instance</label><input data-instance type="number" min="1" max="20" value="${Number(initial.instance)||1}"></div></div>${editing?'':'<div class="qol-rme-expand"><div data-expand class="qol-rme-check active" role="checkbox" tabindex="0" aria-checked="true">✓</div><div><strong>Expand missing levels</strong><small>If Warehouse 3 already exists and you add Warehouse 6, APES adds 4, 5 and 6.</small></div></div>'}<div data-hint class="qol-rme-hint"></div>`,editing?'Save Step':'Add Step');
    const bs=l.querySelector('[data-building]'),lv=l.querySelector('[data-level]'),ins=l.querySelector('[data-instance]'),wrap=l.querySelector('[data-instance-wrap]'),ex=l.querySelector('[data-expand]'),hint=l.querySelector('[data-hint]'),status=l.querySelector('.qol-rm-dialog-status');
    const sync=()=>{const b=entry(bs.value);lv.max=b.max;lv.value=Math.max(1,Math.min(Number(lv.value)||1,b.max));wrap.style.display=b.repeatable?'block':'none';if(!b.repeatable)ins.value=1;const i=b.repeatable?Math.max(1,Number(ins.value)||1):0,p=highest(s.roadmap.steps,b.name,i,editing?index:s.roadmap.steps.length);hint.textContent=editing?`${b.name}: levels 1–${b.max}.`:p?`Highest earlier ${b.name}${b.repeatable?` #${i}`:''}: Level ${p}.`:`No earlier ${b.name}${b.repeatable?` #${i}`:''} step.`};
    bs.onchange=sync;lv.oninput=sync;ins.oninput=sync;if(ex)ex.onclick=()=>{const on=ex.getAttribute('aria-checked')!=='true';ex.setAttribute('aria-checked',on);ex.classList.toggle('active',on);ex.textContent=on?'✓':''};sync();
    l.querySelector('[data-rme-confirm]').onclick=()=>{const b=entry(bs.value),level=Number(lv.value);if(!Number.isInteger(level)||level<1||level>b.max){status.textContent=`Choose a level from 1 to ${b.max}.`;return}const i=b.repeatable?Math.max(1,Math.min(20,Number(ins.value)||1)):null,c=read(),r=c[s.id];if(!r)return;if(editing){r.steps[index]=makeStep(b,level,i);write(c);closeDialog();refresh();toast('Building step updated.');return}const p=highest(r.steps,b.name,i),expand=ex?.getAttribute('aria-checked')==='true';let count=1;if(expand&&level>p){const start=Math.max(1,p+1);count=level-start+1;for(let x=start;x<=level;x++)r.steps.push(makeStep(b,x,i))}else r.steps.push(makeStep(b,level,i));write(c);closeDialog();refresh();toast(count>1?`${count} building steps added.`:'Building step added.')};bs.focus();
  }
  function instruction(index=null){
    const s=state();if(!s.roadmap)return;const editing=Number.isInteger(index),old=editing?s.roadmap.steps[index]:null,l=dialog(editing?'Edit Instruction':'Add Instruction','<label>Instruction</label><textarea data-text rows="6" maxlength="600"></textarea>',editing?'Save Step':'Add Step'),input=l.querySelector('[data-text]'),status=l.querySelector('.qol-rm-dialog-status');input.value=old?.type==='instruction'?old.text:'';
    l.querySelector('[data-rme-confirm]').onclick=()=>{const text=clean(input.value);if(!text){status.textContent='Enter an instruction.';return}const c=read(),r=c[s.id];if(!r)return;const step={type:'instruction',text};if(editing)r.steps[index]=step;else r.steps.push(step);write(c);closeDialog();refresh();toast(editing?'Instruction updated.':'Instruction added.')};input.focus();
  }
  function stepAction(action,index){const s=state(),r=s.roadmap;if(!r||index<0||index>=r.steps.length)return;if(action==='edit')return r.steps[index].type==='building'?building(index):instruction(index);if(action==='up'&&index>0)[r.steps[index-1],r.steps[index]]=[r.steps[index],r.steps[index-1]];else if(action==='down'&&index<r.steps.length-1)[r.steps[index+1],r.steps[index]]=[r.steps[index],r.steps[index+1]];else if(action==='duplicate')r.steps.splice(index+1,0,JSON.parse(JSON.stringify(r.steps[index])));else if(action==='delete')r.steps.splice(index,1);else return;write(s.custom);refresh();if(action==='duplicate')toast('Step duplicated.');if(action==='delete')toast('Step deleted.','info')}
  function controls(i,total){return`<div class="qol-rme-step-actions"><div class="qol-rme-icon${i===0?' disabled':''}" data-rme-step="up" data-index="${i}" role="button" tabindex="${i===0?-1:0}">↑</div><div class="qol-rme-icon${i===total-1?' disabled':''}" data-rme-step="down" data-index="${i}" role="button" tabindex="${i===total-1?-1:0}">↓</div><div class="qol-rme-icon" data-rme-step="duplicate" data-index="${i}" role="button" tabindex="0">⧉</div><div class="qol-rme-icon" data-rme-step="edit" data-index="${i}" role="button" tabindex="0">✎</div><div class="qol-rme-icon danger" data-rme-step="delete" data-index="${i}" role="button" tabindex="0">×</div></div>`}
  function enhance(){const p=document.getElementById(PANEL);if(!p)return;const title=p.querySelector('.qol-rm-sidebar-title');if(title&&!title.querySelector('[data-rme-new]'))title.insertAdjacentHTML('beforeend','<div class="qol-rm-action qol-secondary qol-rme-new" data-rme-new role="button" tabindex="0">+ New</div>');const s=state();if(!s.roadmap)return;const actions=p.querySelector('.qol-rm-actions');if(actions&&!actions.querySelector('[data-rme-details]')){const rename=actions.querySelector('[data-roadmap-action="rename"]');if(rename)rename.outerHTML='<div class="qol-rm-action qol-secondary" data-rme-details role="button" tabindex="0">Edit Details</div>';else actions.insertAdjacentHTML('afterbegin','<div class="qol-rm-action qol-secondary" data-rme-details role="button" tabindex="0">Edit Details</div>')}const head=p.querySelector('.qol-rm-route-head');if(head&&!head.querySelector('[data-rme-add]'))head.insertAdjacentHTML('beforeend','<div class="qol-rme-add"><div class="qol-rm-action qol-secondary" data-rme-add="building" role="button" tabindex="0">+ Building Step</div><div class="qol-rm-action qol-secondary" data-rme-add="instruction" role="button" tabindex="0">+ Instruction</div></div>');const rows=p.querySelectorAll('.qol-rm-route .qol-rm-step');rows.forEach((row,i)=>{row.classList.add('qol-rme-editable');if(!row.querySelector('.qol-rme-step-actions'))row.insertAdjacentHTML('beforeend',controls(i,rows.length))})}
  function init(){document.addEventListener('click',e=>{const p=document.getElementById(PANEL);if(!p)return;const n=e.target.closest('[data-rme-new]');if(n&&p.contains(n))return details(true);const d=e.target.closest('[data-rme-details]');if(d&&p.contains(d))return details(false);const a=e.target.closest('[data-rme-add]');if(a&&p.contains(a))return a.dataset.rmeAdd==='building'?building():instruction();const s=e.target.closest('[data-rme-step]');if(s&&p.contains(s)&&!s.classList.contains('disabled'))return stepAction(s.dataset.rmeStep,Number(s.dataset.index))},true);document.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('[data-rme-new],[data-rme-details],[data-rme-add],[data-rme-step]')){e.preventDefault();e.target.click()}},true);new MutationObserver(()=>requestAnimationFrame(enhance)).observe(document.documentElement,{childList:true,subtree:true});requestAnimationFrame(enhance);window.APES=window.APES||{};window.APES.roadmapsEditor=Object.freeze({buildings:BUILDINGS,enhance})}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();