(() => {
  'use strict';
  const A=window.APES_AOC_INTERNAL,D=A?.data;if(!D)return;
  const X=A.actions={};
  const TOOLS=[
    ['qol-rally-point-toggle-btn','rallyPointParser','Rally Point Scanner'],['qol-roadmaps-toggle-btn','roadmaps','Roadmaps'],['qol-building-alarm-toggle-btn','buildingAlarm','Building Alarms'],['qol-npc-calc-toggle-btn','npcCalculator','NPC Calculator'],['qol-resource-planner-toggle-btn','resourceUpgradePlanner','Resource Upgrade Planner'],['qol-distance-calc-toggle-btn','distanceCalculator','Distance & Arrival Calculator'],['qol-watchlist-toggle','watchlist','Watchlists'],['qol-report-archive-toggle','reportArchive','Report Archive'],['qol-cp-toggle-btn','cpManager','CP Manager'],['qol-oasis-toggle-btn','oasisScanner','Oasis Scanner'],['qol-ss-scanner-toggle-btn','secretSocietyScanner','Secret Society Scanner']
  ].map(([id,key,label])=>({id,key,label}));
  let dragged='';
  const featureEnabled=key=>typeof window.isQolEnabled==='function'?window.isQolEnabled(key)===true:localStorage.getItem(`qol_${key}`)!=='false';
  const orderKey=()=>`apes_aoc_tool_order:${location.hostname}`;
  function order(){const ids=TOOLS.map(x=>x.id);try{const p=JSON.parse(localStorage.getItem(orderKey())||'[]');return Array.isArray(p)?[...p.filter(x=>ids.includes(x)),...ids.filter(x=>!p.includes(x))]:ids;}catch(_){return ids;}}
  function save(ids){try{localStorage.setItem(orderKey(),JSON.stringify(ids));}catch(_){}}
  X.renderTools=()=>{const target=document.querySelector(`#${D.OVERLAY_ID} .apes-aoc2-tools-list`);if(!target)return;const map=new Map(TOOLS.map(x=>[x.id,x]));const tools=order().map(id=>map.get(id)).filter(x=>x&&featureEnabled(x.key)&&document.getElementById(x.id));target.innerHTML=tools.length?tools.map(x=>`<button type="button" class="apes-aoc2-tool" draggable="true" data-tool-id="${D.esc(x.id)}"><i>⋮⋮</i><span>${D.esc(x.label)}</span><b>›</b></button>`).join(''):'<span class="apes-aoc2-side-empty">No enabled toolbar tools detected.</span>';};
  function reorder(from,to){if(!from||!to||from===to)return;const ids=order().filter(x=>x!==from),i=ids.indexOf(to);ids.splice(i<0?ids.length:i,0,from);save(ids);X.renderTools();}
  function route(extra){const id=D.currentVillageId();return`#/page:village${/^\d+$/.test(id)?`/villId:${id}`:''}${extra?`/${extra}`:''}`;}
  function clickNative(selectors,words){for(const s of selectors){const e=document.querySelector(s);if(e){e.click();return true;}}const q=words.map(x=>x.toLowerCase());const e=[...document.querySelectorAll('a,button,[role="button"],[clickable],[ng-click]')].find(x=>{if(x.closest(`#${D.OVERLAY_ID}`))return false;const r=x.getBoundingClientRect(),text=[x.textContent,x.title,x.getAttribute('aria-label'),x.getAttribute('tooltip'),x.getAttribute('tooltip-translate'),x.id,x.className].filter(Boolean).join(' ').toLowerCase();return r.width>0&&r.height>0&&q.some(w=>text.includes(w));});if(e){e.click();return true;}return false;}
  X.quick=action=>{if(action==='hero')location.hash=route('window:hero/herotab:Inventory');else if(action==='rally')location.hash=route('location:32/window:building/cp:1');else if(action==='chat'){location.hash=route('window:igm');setTimeout(()=>clickNative(['#jsQuestButtonIgm'],['message','chat']),60);}else if(action==='statistics')clickNative(['#jsStatisticsButton','[id*="statistic" i]'],['statistics']);else if(action==='auction')clickNative(['#jsAuctionButton','[id*="auction" i]'],['auction']);else if(action==='quests')clickNative(['#jsQuestButton','[id*="quest" i]'],['quest']);};
  X.bind=o=>{o.querySelector('.apes-aoc2-close').onclick=()=>A.controller?.close?.();o.querySelector('.apes-aoc2-refresh').onclick=()=>{D.captureCurrent();A.controller?.request?.();};o.onclick=e=>{if(e.target===o)return A.controller?.close?.();const q=e.target.closest('[data-quick]');if(q)return X.quick(q.dataset.quick);const ev=e.target.closest('[data-event-village-id]');if(ev)return A.controller?.openVillage?.(ev.dataset.eventVillageId);const b=e.target.closest('[data-building-village-id]');if(b)return A.controller?.openBuilding?.(b.dataset.buildingVillageId,b.dataset.buildingLocation);const v=e.target.closest('[data-village-id]');if(v)return A.controller?.openVillage?.(v.dataset.villageId);const t=e.target.closest('[data-tool-id]');if(t)return document.getElementById(t.dataset.toolId)?.click();};o.ondragstart=e=>{const t=e.target.closest('[data-tool-id]');if(t){dragged=t.dataset.toolId;t.classList.add('dragging');e.dataTransfer?.setData('text/plain',dragged);}};o.ondragend=e=>{e.target.closest('[data-tool-id]')?.classList.remove('dragging');dragged='';};o.ondragover=e=>{if(e.target.closest('[data-tool-id]'))e.preventDefault();};o.ondrop=e=>{const t=e.target.closest('[data-tool-id]');if(t){e.preventDefault();reorder(dragged||e.dataTransfer?.getData('text/plain'),t.dataset.toolId);}};};
})();
